### ISSUE TITLE
`modules:` extend `tt.yaml` to support a list in `modules/directory`

### ISSUE THREAD

**Issue by dmyger** [tarantool/tt#1012]
The logic of working with the configuration file tt.yaml should be updated, allowing to specify modules/directory both as a single line and as a list.

By default, should be a single entry:
```yaml
modules:
  directory: /path/to/ext/tt/modules
```

And it should accept a list of directories:
```yaml
modules:
  directory:
    - modules
    - /path/to/ext/tt/modules
```

If a relative path is specified, the search is performed in the subfolders below, relative to the `tt.yaml` file. If an absolute path is specified, external modules are searched according to the specified path.
When creating a new configuration file, the default configuration should have only the single `modules` folder is defined.

**Comment by oleg-jukovec** [comment]
Unfortunately #1032 breaks tests on full-ci so I've reverted it in #1042 to not block other tasks. We'll have to try again.
