### ISSUE TITLE
cat: allow to specify multiple WAL files

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/tt#1019]
We need to have an ability to have an ability to specify multiple WAL files. It could be done in different ways:

1. Just to allows pass files as additional args (I prefer this way).
   `tt cat 1.xlog 2.xlog`
2. Add an additional flag `--wal` to specify a WAL file and allows to use the flag multiple:
   `tt cat --wal 1.xlog --wal 2.xlog`
3. Mixed 1 + 2.

**Comment by patapenka-alexey** [comment]
This functionality is already implemented:
```shell
 $ ./tt cat ./00000000000000000000.xlog ./00000000000000000000.snap ./00000000000000000012.xlog ./00000000000000000012.snap | grep Result
   • Running cat with files: [./00000000000000000000.xlog ./00000000000000000000.snap ./00000000000000000012.xlog ./00000000000000000012.snap]

• Result of cat: the file "./00000000000000000000.xlog" is processed below •
• Result of cat: the file "./00000000000000000000.snap" is processed below •
• Result of cat: the file "./00000000000000000012.xlog" is processed below •
• Result of cat: the file "./00000000000000000012.snap" is processed below •
```

**Comment by oleg-jukovec** [comment]
> Part of this functionality is already implemented:
> 
>  $ ./tt cat ./00000000000000000000.xlog ./00000000000000000000.snap ./00000000000000000012.xlog ./00000000000000000012.snap | grep Result
>    • Running cat with files: [./00000000000000000000.xlog ./00000000000000000000.snap ./00000000000000000012.xlog ./00000000000000000012.snap]
> 
> • Result of cat: the file "./00000000000000000000.xlog" is processed below •
> • Result of cat: the file "./00000000000000000000.snap" is processed below •
> • Result of cat: the file "./00000000000000000012.xlog" is processed below •
> • Result of cat: the file "./00000000000000000012.snap" is processed below •

Nice, please, update help than.
