### ISSUE TITLE
tt completion

### ISSUE THREAD

**Issue by unera** [tarantool/tt#11]
The module provides integration with bash/zsh completion system.

`tt completion argument[,argument...] ` suggests about `tt argument[,argument...]`

**Comment by LeonidVas** [comment]
Now completion has been implemented for the internal modules. Further work on the module will be carried out as part of the tasks:
- [ ] https://github.com/tarantool/tt/issues/44
- [ ] https://github.com/tarantool/tt/issues/45
- [ ] https://github.com/tarantool/tt/issues/46
