### ISSUE TITLE
Implement packaging and CD

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#110]
In fact, users prefer to use a package managers like `yum`, `apt` ... to get the tool they need instead of `git clone ... && mage build`. We need to implement packaging to `rpm` and `deb` packages and add GHA to deliver packages to our S3 repository ([modules](https://rws.tarantool.org/release/modules)).

**Comment by LeonidVas** [comment]
I recommend looking at the [cartridge-cli implementation](https://github.com/tarantool/cartridge-cli/blob/0dd4e3aa5a5110b6b61dc656557cd98526808232/magefile.publish.go).

**Comment by Totktonada** [comment]
NB: I think that packages, source tarballs and a brew formula should use `tarantool-tt` name. We usually package tarantool modules this way.
