### ISSUE TITLE
Tests: cleanup running tarantool instances if test failed.

### ISSUE THREAD

**Issue by 0x501D** [tarantool/tt#128]
At the moment, if the cartridge tests fail (test/integration/cartridge/test_cartridge.py), then running instances of tarantool remain.
Before restarting the tests, you must manually shut down these services. It is necessary to automatically shut down tarantool instances in case of test failures. It is also necessary to check the rest of the integration tests for the presence of this problem.

**Comment by oleg-jukovec** [comment]
Maybe it will be useful:
https://github.com/tarantool/go-tarantool/issues/147#issuecomment-1172426780

**Comment by GRISHNOV** [comment]
Perhaps it will be useful, take a look at the commit with the name `test: add mechanism for auto instances kill` from [PR](https://github.com/tarantool/tt/pull/112)
