### ISSUE TITLE
tt rocks

### ISSUE THREAD

**Issue by unera** [tarantool/tt#14]
see `tarantoolctl rocks`

**Comment by Totktonada** [comment]
The following issues were found as part of this task:

- https://github.com/yuin/gopher-lua/issues/360
- https://github.com/yuin/gopher-lua/issues/363

We forked gopher-lua and fixed it in our fork:

- https://github.com/tarantool/gopher-lua/pull/1
- https://github.com/tarantool/gopher-lua/pull/2

And also proposed those changes to the upstream:

- https://github.com/yuin/gopher-lua/pull/361
- https://github.com/yuin/gopher-lua/pull/364

As well as one more fix to the upstream (our fork in not affected):

- https://github.com/yuin/gopher-lua/pull/366

If all changes will be accepted by the upstream, I'll just drop the fork.
