### ISSUE TITLE
Add colors to search

### ISSUE THREAD

**Issue by better0fdead** [tarantool/tt#146]
I propose to highlight already installed versions when using 'tt search'

**Comment by 0x501D** [comment]
I suggest not using color for this. Better something like this:

```sh
$ tt search tarantool --local-repo
   • Available versions of tarantool:
1.10.0
1.10.1 [installed]
1.10.2
1.10.3
```

**Comment by better0fdead** [comment]
Also we can highlight versions, that are already stored in distfiles directory. like [downloaded[
