### ISSUE TITLE
Error strings should not be capitalized

### ISSUE THREAD

**Issue by 0x501D** [tarantool/tt#150]
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

In tt, a lot of error messages are not written according to the rules of golang code review. Needs to be corrected.

Also add linter to CI:(https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-format)

**Comment by oleg-jukovec** [comment]
> Also add linter to CI:(https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-format)

Probably, we can just to enable the `errorlint` linter for golangci-lint here:

https://github.com/tarantool/tt/blob/master/golangci-lint.yml

https://golangci-lint.run/usage/linters/

[errorlint](https://github.com/polyfloyd/go-errorlint) [⚙️](https://golangci-lint.run/usage/linters/#errorlint)	errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
