### ISSUE TITLE
tt install, tt remove

### ISSUE THREAD

**Issue by unera** [tarantool/tt#17]
Installs tarantool or tt (or tt modules or something else) into the current bundle.

```
tt install tarantool=2.6.1
tt remove tarantool

tt install -s tarantool=2.5.1
```

Options:

- `-s` - build and install
checks build-depends and prints a command to install them if any of them is not found.

**Comment by LeonidVas** [comment]
The task was split to several subtask:
- [ ] https://github.com/tarantool/tt/issues/91
- [ ] https://github.com/tarantool/tt/issues/92
- [ ] https://github.com/tarantool/tt/issues/94
- [ ] https://github.com/tarantool/tt/issues/95
- [ ] https://github.com/tarantool/tt/issues/96
- [ ] https://github.com/tarantool/tt/issues/97
