### ISSUE TITLE
Add license checker to CI

### ISSUE THREAD

**Issue by 0x501D** [tarantool/tt#205]
We need to check the licenses of modules that came from dependencies.
CI should return an error if the licenses are not in the list:

* BSD-2
* MIT
* Apache-2.0
* BSD
* MPL-2.0

Checker example:
```sh
GITHUB_TOKEN='XXX' golicense  -plain ./dist/tt_linux_amd64_v1/tt 
github.com/briandowns/spinner             Apache License 2.0
github.com/mitchellh/mapstructure         MIT License
github.com/vmihailenco/tagparser          BSD 2-Clause "Simplified" License
```

**Comment by Totktonada** [comment]
NB: I had successful experience with [lichen](https://github.com/uw-labs/lichen), see my results [here](https://github.com/tarantool/gentoo-overlay/pull/59#discussion_r1007447419).
