### ISSUE TITLE
Make run greate again

### ISSUE THREAD

**Issue by 0x501D** [tarantool/tt#210]
Need to change the behavior of the tt run command:

* tt run should only run the specified scripts. E.g.:
```sh
$ tt run foo.lua
$ tt run /tmp/foo.lua
```
* tt run should not start instances.
* tt run must pass arguments to the script. E.g.:
```sh
$ tt run foo.lua -- a b c
```

* tt run must read and use only `data_dir` from tarantol.yaml

**Comment by LeonidVas** [comment]
`tt run` shouldn't create console socket, PID file...
`tt run` shouldn't run applications from `instances.enabled`.

**Comment by better0fdead** [comment]
* `tt run` shouldn't create console socket, PID file...
tt run doesn't create any artifacts.
* tt run must pass arguments to the script. E.g.:
```sh
$ tt run foo.lua -- a b c
```
with Lua files it works
```sh
$ cat test.lua
print(arg[1])
$ ./tt run test.lua -- 123
123
```
With -e it is broken, yes
*  tt run should not start instances.
tt run doesn't start instances, log message Is incorrect and should be removed.
It runs lua script through launcher.lua if it is script is specified.
