### ISSUE TITLE
tt import/tt export

### ISSUE THREAD

**Issue by unera** [tarantool/tt#24]
```bash
tt import name -format csv -space users users.csv
tt import name -format csv -space users < file.csv

tt export name -format csv -space users users.csv
tt export name -format csv -space users > users.csv

```

Options:

- `--format` - file format (CSV is default)
- `--space` - space name for import/export. Required option
- `--match name1=csvrow1:name2=csvrow2:...` - Match for CSV and space fields **for import and export**.
   - csvrow is CSV row number (from 1 to N)
   - name - is field name or field number
- `--header=on|off` - (`off` - default).
   - `on` - export fieldnames to the first CSV line, import fieldnames from the first CSV line (can raise error)
   - `off` - the first CSV line is a data line

You could make alias `--match header` and `--header on`.

Import (only) options:

- `--progress {file}` - use the file to store import progress

If the option "`match`" option doesn't contain any primary key fields, the utility will generate a primary key for each record: autoincrement for `numeric` fields, UUID-string for `string` fields, `UUID` for `UUID` fields.

- `--failed {skip|error}` - behaviour with error tuples (example duplicate key or constraint errors)
- `--update {new|all}` - update exists records or create new only. (The option means something if PK is present in input CSV)

**Comment by LeonidVas** [comment]
Moved to tt-ee repository.
