### ISSUE TITLE
Add the ability to pass arguments for a function called with `eval`

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#256]
Needs to add the ability to pass arguments for a function called with `eval` through the `tt connect` module.

**Comment by oleg-jukovec** [comment]
```bash
$ echo 'print(...)' | tt connect $URL -f- Hello world
```

**Comment by oleg-jukovec** [comment]
Unfortunately, `console.eval(...)` (connect uses the call as a wrapper) does not supported. It also does not support something like this:
```Lua
console.eval('print(...)', 1, 2, 3)
```
So it might be a little more difficult.

https://github.com/tarantool/tarantool/blob/c561202d732650f263957d6c8ee348be307beeda/src/box/lua/console.lua#L431-L433
