### ISSUE TITLE
Failed to replace cartridge pack with tt pack

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tt#280]
May be reproduced as follows.

For example, you may use clean Ubuntu installation in docker.

```bash
docker run -it ubuntu:20.04
```

### 1. Prepare the environment.

```bash
apt-get update
apt-get install -y curl
```

#### Prepare repo.

```bash
curl -L https://tarantool.io/release/2/installer.sh | bash
apt-get update
```

#### Install tarantool.

```bash
apt-get install -y tarantool tarantool-dev
```

#### Install cartridge-cli.

```bash
apt-get install -y cartridge-cli
cartridge --version
Tarantool Cartridge CLI
 Version:	2.12.3
 OS/Arch: 	linux/amd64
 Git commit:	004186a
```

#### Install tt.

```bash
apt-get install -y tt
tt version
Tarantool CLI version 0.3.0, linux/amd64. commit: 8be6db8
```

### 3. Create a template application

```bash
cartridge create --name myapp
cd ./myapp
```

#### With `cartridge-cli`.

```bash
cartridge pack rpm --version 1.0.0
   • Application was successfully packed
```

#### With tt

```bash
tt pack rpm --version 1.0.0   
   ⨯ failed to pack: lstat /etc/tarantool/modules: no such file or directory
```

**Comment by vr009** [comment]
Hi, thank you for your feedback!

I would like to leave some comments to explain this behavior.

0. About tt behavior. `tt` use `tarantool.yaml` file for self-configuration. So, the first thing, that happens after running tt (except tt init and tt create), it searches for the configuration file. If there is no this file in the CWD it will go up until the root and if it finds nothing it will try to use the system config, located in `/etc/tarantool`.

1. `tt` package was installed with system `tarantool.yaml` config located in `/etc/tarantool`, where we have the next snippet:
```yaml
tt:
  modules:
    # Directory where the external modules are stored.
    directory: modules
...
...
```

We have a `modules` directory set, but in `/etc/tarantool` it is not created.
Looks like it is not only pack issue, I can patch it, but it will only warn you that this directory doesn't exist.

2. Cartridge cli creates an application from template without any `tarantool.yaml` config. So after starting `tt` it will search for the the config and find only the system one (which was installed with your package manager). This way, `tt` will search for applications in `instances_enabled` path from the config (actually `/etc/tarantool/instances.enabled` in your case). So you don't get the correctly working packing.

3. If you want to go this way, that you creates an app with cartridge-cli and use tt for packing, you need additionaly to create `tarantool.yaml` with minimal contents:
```
tt:
  app:
    instances_enabled: .
```

4. If you are going to replace cartridge-cli with tt-cli, you should follow the next steps for creating an app and packing it:
```bash
$ tt init
$ tt create cartridge --name myapp
$ tt pack --version 0.1.0
```

**Comment by DifferentialOrange** [comment]
> 4. If you are going to replace cartridge-cli with tt-cli, you should follow the next steps for creating an app and packing it:

`init` declares that I can create an environment config for an application:

`init Create tt environment config for application in current directory`

so there seems to be no reason to call `tt init` before I have any application.

Running `tt create cartridge --name myapp` fails on a clean installation:

```
tt create cartridge --name myapp
   • Creating application in /myapp
   • Using built-in 'cartridge' template.
   • Application 'myapp' created successfully
   • Failed to enable myapp application: symlink ../../../myapp /etc/tarantool/instances.enabled/myapp: no such file or directory
```

**Comment by vr009** [comment]
tt init is also needed for instantiating your environment. After this command you will have the next structure:
```bash
> $ tree .
.
├── bin
├── distfiles
├── include
├── instances.enabled
├── modules
├── tarantool.yaml
└── templates
```

Then you may call `tt create cartridge --name myapp` and this will instantiate a cartridge template app in your current environment.

**Comment by vr009** [comment]
>    • Failed to enable myapp application: symlink ../../../myapp /etc/tarantool/instances.enabled/myapp: no such file or directory

That is a bug btw, but already fixed AFAIK. `tt create` must work without any config file.

**Comment by DifferentialOrange** [comment]
> `tt init` is also needed for instantiating your environment.

Again, "init creates tt environment config for application in current directory". I don't get why I should init environment for an application before I have any applications.

**Comment by DifferentialOrange** [comment]
Either way, I don't see any reason why I shouldn't be able to pack an RPM of my application if it was instantiated with `cartridge create`.

**Comment by DifferentialOrange** [comment]
> We have a `modules` directory set, but in `/etc/tarantool` it is not created.
> Looks like it is not only pack issue, I can patch it, but it will only warn you that this directory doesn't exist.

It would be nice to have `tt` work out-of-the-box with system config since we provide it. On the other hand, I don't get why `pack` needs any global directory: I expect it to take some local files and get some result (rpm package) in `.`, maybe by using `/tmp` in-between.

**Comment by DifferentialOrange** [comment]
The problem is I don't quite get what exact configuration is missing for `tt pack`. If default setting is something other than "take some local files and get some nice result (rpm package) in `.`", I have no idea what it may be.

**Comment by vr009** [comment]
> > `tt init` is also needed for instantiating your environment.
> 
> Again, "init creates tt environment config for application in current directory". I don't get why I should init environment for an application before I have any applications.

The `init` help output should be clarified, I agree... The thing is that `init` also creates standard directories for your new environment and generates a new `tarantool.yaml` config with corresponding paths. This way we urge users to go with the new common approach of developing with tarantool and tt.

> Either way, I don't see any reason why I shouldn't be able to pack an RPM of my application if it was instantiated with cartridge create.

Yes, it could, but we rely on the new common approach of managing tarantool apps using `tt`. That new approach needs a basic `tarantool.yaml` file.

> The problem is I don't quite get what exact configuration is missing for tt pack. If default settings for pack are something other than "take some local files and get some nice result (rpm package) in .", I have no idea what it may be.

`tt pack` basically needs to know where in the current environment instances.enabled directory is located. `instances.enabled` directory contains symlinks and sources of applications in your environment. If you don't want to work with such directories and want to make tt consider the current directory as application, you are free to use the config with instanecs.enabled value `.`.

**Comment by DifferentialOrange** [comment]
Let me at least run `tt pack rpm .`. I don't get why I need six directories and one yaml to pack my RPM.
