### ISSUE TITLE
replicaset: implement `bootstrap` / `rebootstrap` commands

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#316]
Implement `bootstrap` / `rebootstrap` commands.

**Comment by askalt** [comment]
Was decided to implement:
`tt vshard bootstrap` - bootstraps vshard in cartridge/3.0 cluster.
`tt bootstrap` - bootstraps an instance in cartridge/3.0 replicaset (by the fact, new instance joins to the replicaset)
`tt reboostrap` - restarts an instance in the replicaset trying to save uuid, if it could be done.
