### ISSUE TITLE
Support overriding of the tt environment configuration with environment variables.

### ISSUE THREAD

**Issue by psergee** [tarantool/tt#471]
tt should consider environment, when working with some directories. Environment variables to support:
- `TT_CLI_REPO_ROCKS_PATH`: check directory `tt.app.repo.rocks` for rocks repo manifest (`manifest` file). If it exists, use this dir as rock repo path. If not, check for the env var. If it is set, use it as a rocks repo path.

- `TT_CLI_TARANTOOL_INCLUDE_PATH`: If tarantool executable is system, and this variable is set, use it instead of `tt.app.inc_dir` for the following commands: build, rocks, pack, cfg. `install` and `uninstall` commands should ignore this variable and install/install tarantool headers to/from `tt.app.inc_dir`. If tarantool is installed by `tt`, ignore this var and use `tt.app.inc_dir`. If the variable is not set, also use `tt.app.inc_dir`.

**Comment by opomuc** [comment]
Probably related with https://github.com/tarantool/tt/issues/470 as well
