### ISSUE TITLE
it is not clear where tarantool is installed

### ISSUE THREAD

**Issue by ligurio** [tarantool/tt#483]
```
[0] ~/sources/MRG/tarantool$ tt install tarantool 2.11.0
   • Checking existing...     
   • Installing tarantool=2.11.0
   • Checking dependencies... 
   • Downloading tarantool... 
   • Patching tarantool...    
   • Building tarantool...    
   • Copying executable...    
   • Copying headers...       
   • Changing symlinks...     
   • Done.                    
[0] ~/sources/MRG/tarantool$ man tt
No manual entry for tt
[0] ~/sources/MRG/tarantool$ 
```

Please add a message with a text like this:

"tarantool executable is installed to /opt/tarantool/bin/tarantool_2.11.0 and made default by symlink to /opt/tarantool/bin/tarantool. It is worth adding /opt/tarantool/bin to a PATH: export PATH=$PATH: /opt/tarantool/bin/".

**Comment by Japsty** [comment]
I would like to work on this issue. Could you please assign it to me?
