### ISSUE TITLE
connect: research for possible ways to add support for multi-line commands in history

### ISSUE THREAD

**Issue by askalt** [tarantool/tt#485]
Multi-line commands are not supported at the moment, i.e. `tt connect` history shows multi-line commands line by line.
Research for possible ways to fix.

**Comment by Totktonada** [comment]
Where can I find the results of the research if it is done? Is there a task to track status of the multiline commands support in tt's REPL?

**Comment by askalt** [comment]
Hi!
It was decided to add support for multi-line commands  to the `go-prompt` fork.
There is [Pull Request](https://github.com/tarantool/go-prompt/pull/1), which introduces it.
