### ISSUE TITLE
connect: need to add info about the keyboard shortcuts 

### ISSUE THREAD

**Issue by askalt** [tarantool/tt#541]
Need to add information about the keyboard shortcuts that the user can use in the prompt.

**Comment by kyukhin** [comment]
Could you please provide a few examples of such (tt-specific) shortcuts?

**Comment by askalt** [comment]
Since the behavior of some key combinations has been enhanced (https://github.com/tarantool/tt/pull/540), it seems logical to add somewhere a description of supported combinations. For example, certain emacs-like key combinations, such as ctrl+A/E/P/etc., are now supported.
