### ISSUE TITLE
Update/extend the functionality of the `tt connect` module

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#58]
* The eval (`console.eval`) should be used only in cases:

1. `tt connect -f FILE_NAME`
2. `COMMAND | tt connect -f -`

* Add `-x` option enables a mode where all executed commands are printed to the terminal (trace mode like in [bash](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html))
* Add `--language` option (Lua(`\set language lua`), SQL(`\set language sql`))

**Comment by LeonidVas** [comment]
Add possibility to pass credentials through URI.

**Comment by LeonidVas** [comment]
A few more wishes:
- pass credentials via env. vars, as in the AWS CLI
- `COMMAND | tt connect ` should execute commands line by line and leave the connection console to continue working after

**Comment by unera** [comment]
> Add -x option enables a mode where all executed commands are printed to the terminal (trace mode like in [bash](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html))
>    Add --language option (Lua(\set language lua), SQL(\set language SQL))

stop

to be like as bash - wrong idea, it would be nice be similar to psql

so

- `-x sql`
- `-x lua`
- (future): `-x table,yaml,table,sql` 
- etc

**Comment by oleg-jukovec** [comment]
The problem with traces:

If we start executing valid commands one by one via connector eval then we are facing a problem:
```
console.eval("local i = 10")
console.eval("return i")
```

is not equal to:

```
console.eval("local i = 10\nreturn i")
```

So it will be different behavior in case `file.lua`:
```Lua
local i = 10
return i
```
and tt connect -f file.lua with/without -trace option.


A patch file to play:
[trace.patch.txt](https://github.com/tarantool/tt/files/9582766/trace.patch.txt)

**Comment by oleg-jukovec** [comment]
Tarantool does not have SQL autocompletion: https://github.com/tarantool/tarantool/issues/2304

**Comment by oleg-jukovec** [comment]
Let's summarize:

There is only one wish left here `Add -x option enables a mode where all executed commands are printed to the terminal (trace mode like in [bash](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html))`. See also: https://github.com/tarantool/tt/issues/58#issuecomment-1249139450

**Comment by LeonidVas** [comment]
For the input language selection option we left `-l` . `-x` will probably be used to select the output format (`table,yaml`).
