### ISSUE TITLE
`tt` connection console hangs during typing commands if delimiter is set

### ISSUE THREAD

**Issue by psergee** [tarantool/tt#727]
Steps to reproduce:
```
$ tt connect <uri>

> \set delimiter ;

> print('123456');
```
Console is hanging during typing `print('123456');` line. This is due to invocation of the completion handler lua code. After setting a delimiter `tarantool` expects the code to end with the specified delimiter. But `tt` built-in lua code does not have this delimiter at the end and the code is not invoked on the server side, so the console waits for 3 sec for each symbol. And it hangs completely after `;` and enter. Probably due to the same reason.

**Comment by p7nov** [comment]
Stumbled upon the same issue on tt 2.1.0 on macOS.

```
tt-user@ubuntu-server:~/testapp$ tt version
Tarantool CLI version 2.1.0, linux/amd64. commit: d7bce7d
```

After entering `\set delimiter ;`, the tt console doesn't execute anything including `\quit` and doesn't respond to `ctrl+c` and `ctrl+d`. The only thing that helps is ``tt restart`` from another terminal.

![image](https://github.com/tarantool/tt/assets/42832629/a9fbe060-d6ea-4924-9e33-4742e55f51b6)

**Comment by dmyger** [comment]
![Steps to reproduce](https://github.com/user-attachments/assets/9978d6da-e203-473a-b1b2-ffba9b2cbc30)
