### ISSUE TITLE
Fix github.com rockspecs according to https://github.com/tarantool/luarocks/pull/11

### ISSUE THREAD

**Issue by ochaton** [tarantool/tt#74]
Github changed policy of cloning repository, and forces now to specify git+https protocol to fetch sources.

There are plenty of rockspecs published in luarocks.org which has old url format: git://github.com.

Hisham already fixed this behavior in luarocks:3.8.0 and we should take his commit to our fork of luarocks

See: https://github.com/tarantool/luarocks/pull/11

**Comment by Totktonada** [comment]
Related: https://github.com/tarantool/tarantool/issues/6597.

**Comment by Totktonada** [comment]
I would just update luarocks (in tarantool and tt both).

**Comment by ochaton** [comment]
Good idea! @Totktonada will you create new PR?
