### ISSUE TITLE
Update luarocks dependency to the latest version

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tt#811]
There were an [issue](https://github.com/luarocks/luarocks/issues/1529) in the parent luarocks/luarocks repository: `luarocks pack` would pack a rock and name it `x86_64` instead of `arm64` even if the rock itself has been built for arm.

It was fixed in 3.10 version of luarocks, but 3.11 is already available.

The related issue has been created couple months ago in https://github.com/tarantool/luarocks/issues/19.

Please update luarocks dependency so those with apple silicon chips are able to pack rocks correctly

**Comment by oleg-jukovec** [comment]
Update to luarocks 3.10 does not fix the problem.

**Comment by oleg-jukovec** [comment]
We have a problem with luarocks 3.10.0 ( #920 ), so we revert the update.
