### ISSUE TITLE
Support the manual master switch using the failover coordinator

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tt#822]
Something like the following.

```sh
$ tt failover switch i-002 [--timeout 10] [-d]
<..here command updates are shown if -d is omitted..>
```

See https://github.com/tarantool/tarantool-ee/pull/759 for details.

**Comment by askalt** [comment]
Now, we have `tt cluster replicaset promote/demote/expel`. The commands patch the config in etcd to make some action.

How do you think, can we name it `tt cluster replicaset switch`?

**Comment by Totktonada** [comment]
I don't mind any solution, in fact.

However, I expect that there may be more commands related to failover coordinators and it may be convenient to have a namespace for them.
