### ISSUE TITLE
Improve data display in table/ttable mode

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tt#832]
Improve data display in table/ttable mode by adding a format information (fields name).
Only for tarantool >= 3.0

**Comment by oleg-jukovec** [comment]
The original pull request introduces `table` and `ttable` output formats for the `tt console`:
https://github.com/tarantool/tt/pull/535

**Comment by oleg-jukovec** [comment]
Blocked by: https://github.com/tarantool/tarantool/issues/10005

We discussed the issue with @sergepetrenko and decided to implement it by us.

**Comment by oleg-jukovec** [comment]
The idea is here to implement [console.eval](https://github.com/tarantool/tarantool/blob/b32b20c6640bb0b1a6ca278bad8061529d46b5b0/src/box/lua/console.lua#L400-L441) analogue in the file:
https://github.com/tarantool/tt/blob/master/cli/connect/lua/console_eval_func_body.lua

And call it instead. The difference will be after the line:
https://github.com/tarantool/tarantool/blob/b32b20c6640bb0b1a6ca278bad8061529d46b5b0/src/box/lua/console.lua#L428

Here we need to transform raw tuples and form a table with metadata(format) in the `SQL` manner:
```
> box.execute([[SELECT * FROM SEQSCAN TABLE1;]])
---
- metadata:
  - name: COLUMN1
    type: integer
  - name: COLUMN2
    type: string
  lua: true
  rows:
  - [10, 'Hello SQL world!']
  - [20, 'Hello LUA world!']
...
```
As result, we will able to print the data in table/ttable/Lua/yaml format on the `tt` side.
