### ISSUE TITLE
`tt status`: show RO/RW status

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tt#835]
It is very useful piece of information.

For example, we expect that one instance is RW and all the other ones are RO. If all the instances are RO, it means that something unexpected occurred.

**Comment by 0x501D** [comment]
visually something like that?:

```
tt status 
INSTANCE         STATUS             PID         MODE
app:instance1    RUNNING            42          RW
app:instance2    RUNNING            24          RO
```

**Comment by Totktonada** [comment]
@0x501D Seems nice!
