### ISSUE TITLE
Publish workflow and tests on self-hosted mac os runners do not work.

### ISSUE THREAD

**Issue by psergee** [tarantool/tt#840]
Currently full ci tests do not pass on mac os due to already running etcd processes on self-hosted runners.
tt packaging (`publish` workflow) also fails after mac os version update on github runners:

> In file included from ../../../../go/pkg/mod/github.com/tarantool/go-openssl@v0.0.8-0.20230307065445-720eeb389195/alloc.go:3:
> ./shim.h:21:10: fatal error: 'openssl/bio.h' file not found
> #include <openssl/bio.h>
>          ^~~~~~~~~~~~~~~
> 1 error generated.

**Comment by oleg-jukovec** [comment]
It could be enough to install openssl directly with `brew`:

https://github.com/tarantool/go-openssl/blob/576e43d9a6ce4634345a58e35cd85ce47bc1a4bd/README.md?plain=1#L28

**Comment by oleg-jukovec** [comment]
It could although help:
https://github.com/tarantool/go-openssl/blob/576e43d9a6ce4634345a58e35cd85ce47bc1a4bd/build.go#L22-L25

or

https://github.com/tarantool/go-openssl/blob/576e43d9a6ce4634345a58e35cd85ce47bc1a4bd/build_static.go#L22-L25

(maybe some paths have been changed)
