### ISSUE TITLE
tt install tt master does not update link

### ISSUE THREAD

**Issue by ochaton** [tarantool/tt#854]
tt allows user to update current version of tt specifying tagged-version, branch and gh issue. I want to experience earliest features of tt, so I want to have latest version of tt (tt master).

Now, when I type `tt install tt master` tt says me that `tt_master` is already installed. Please add checks that tt_master has been updated on github and fetch/install new version

**Comment by oleg-jukovec** [comment]
It looks like a linked issue: https://github.com/tarantool/tt/issues/690
