### ISSUE TITLE
ci: tests don't clean tarantool instances after running on macOS

### ISSUE THREAD

**Issue by themilchenko** [tarantool/tt#912]
There is an [error](https://github.com/tarantool/tt/actions/runs/10019924163/job/28038909739) occurs when unit tests running on macOS:
```
 Failed to prepare test tarantool: failed to dial: dial tcp 127.0.0.1:3013: connect: connection refused
```
Need to find why tests not killing instance on 3013 port. Temporary this problem has been resolved by killing all tarantool processes in [macOS CI](https://github.com/tarantool/tt/pull/908).

**Comment by oleg-jukovec** [comment]
Thank you!

**Comment by themilchenko** [comment]
I was wrong. There weren't not closed `tarantool` instances after tests run. The instance did not start because of the startup options set, so the `connection refused` error is due to a connection at a non-existent address.

**Comment by themilchenko** [comment]
Also it is a problem related with `cli/connnector/integration_test.go` and `cli/replicaset/integration_test.go` tests. When the first one finishes, the second fails sometimes with `connection refused`. 

Something not cleaning after `connector` finishes. I tried to research for this and found following:

-  Processes were killed after test after test finishes.
- There is no addresses with provided ports that LISTEN or ESTABLISH after test finishes.

Changing port of tarantool instance different from the `connector` test fixes problem. For now this problem has resolved this way.
