### ISSUE TITLE
tt install for non-stable identifiers is cached

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tt#925]
`tt install tarantool master` fetches current master commit and builds a binary. If some other tarantool was installed later, after running `tt install tarantool master` one more time tt 2.4.0 checks out installed master.
```bash
   • Checking existing...     
   • tarantool_master version of tarantool already exists, updating symlinks...
   • Done
```

But in case the master was updated and I want to install newer master, I don't have any flag to rebuild and reinstall checked-out version. Moreover, maybe the best solution is to automatically reinstall master in case the branch have changed.

As far as I understand, the issue is related not only to the master branch, but any branch install.

**Comment by oleg-jukovec** [comment]
It is bug, should be fixed with: https://github.com/tarantool/tt/pull/888

**Comment by oleg-jukovec** [comment]
So what behavior do you want?

Re-install/re-build a latest commit on the `master` branch?
Re-install/re-build a commit that was installed before?

**Comment by DifferentialOrange** [comment]
It seems that you work faster than I update my binaries
